#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

find images | grep '\.erd$' | parallel cat {} '|' erd -f png '>' {}.png

_includes/code-in-postgres/compare-results _includes/code-in-postgres/in-order-by-limit

_includes/code-in-postgres/compare-results _includes/code-in-postgres/inner-join

parallel cat {} '|' psql -H '>' _includes/code-in-postgres/bin/{/.}.result.html ::: _includes/code-in-postgres/inner-join.sql _includes/code-in-postgres/in-order-by-limit.sql _includes/code-in-postgres/with.sql

./add-project-readme ./_posts/2019-06-14-hacky-tools-for-postgresql.md ../psql-tools postgresql

./add-project-readme ./_posts/2019-07-05-jdbc-pipe-jdbc-pipe-quick-jdbc-queries-respecting-unix-conventions-environmental-variables-stdin-stdout.md ../jdbc-pipe "postgresql sql jdbc unix stdin stdout"



killall jekyll || true
jekyll clean
jekyll build
./update-blog-files > files.tf
terraform apply -state=_private/terraform.tfstate .

