#!/bin/bash

find images | grep '\.erd$' | parallel cat {} '|' erd -f png '>' {}.png

killall jekyll
jekyll clean
jekyll build
./update-blog-files > files.tf
terraform apply -state=_private/terraform.tfstate .
