/**
 * Ties together the above code, telling PostgreSQL how to construct the
 * the aggregate
 */
create aggregate fail_champ_champ_points(code varchar) (
    stype = ...
    initcond = ...
    sfunc = ...
    finalfunc = ...
);
